version: "3"

services:
  # minecraft.server:
  #   container_name: minecraft.server
  #   image: itzg/minecraft-server
  #   restart: unless-stopped
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - 25565:25565
  #   volumes:
  #     - ./minecraft-data:/data
  #   environment:
  #     - EULA=TRUE
  #     - VERSION=1.20.2
  #     - MEMORY=3G
  #     - RCON_PASSWORD
  minecraft.notifier:
    container_name: minecraft.notifier
    build: ./telegram
    restart: unless-stopped
    volumes:
      - ./telegram-data:/data
      - /home/minecraft/server/logs:/logs
    environment:
      - BOT_TOKEN

  minecraft.bot:
    container_name: minecraft.bot
    build: ./telegram
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./telegram-data:/data
    environment:
      - BOT_TOKEN
      - RCON_PASSWORD
    command: ["python", "-u", "/bot.py"]
