version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
    environment:
      - EULA=TRUE
      - VIRTUAL_HOST=mycraf.tk
      - VIRTUAL_PORT=25565
