version: "3"

services:
  minecraft.server:
    image: itzg/minecraft-server
    container_name: minecraft.server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-data:/data
    environment:
      - EULA=TRUE
      - VERSION=1.20.2
      - MEMORY=3G
      - RCON_PASSWORD
  minecraft.notifier:
    build: ./telegram
    container_name: minecraft.notifier
    restart: unless-stopped
    depends_on:
      - minecraft.server
    environment:
      - BOT_TOKEN
    volumes:
      - ./telegram-data:/data
      - ./minecraft-data/logs:/logs
  minecraft.bot:
    build: ./telegram
    container_name: minecraft.bot
    restart: unless-stopped
    depends_on:
      - minecraft.server
    environment:
      - BOT_TOKEN
      - RCON_PASSWORD
    volumes:
      - ./telegram-data:/data
    command: ["python", "-u", "/bot.py"]
